base/urls.py
from django.urls import path
from base import views

app_name = "base"


urlpatterns = [
    path("", views.index, name="index"),
    path("service/<service_id>/", views.service_detail, name="service_detail"),
    path("book-appointment/<service_id>/<doctor_id>/", views.book_appointment, name="book_appointment"),
    path("checkout/<billing_id>/", views.checkout, name="checkout"),
]

hms_prj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

patient/urls.py
from django.urls import path
from patient import views

app_name = "patient"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("appointments/", views.appointments, name="appointments"),
    path("appointments/<appointment_id>/", views.appointment_detail, name="appointment_detail"),
    
    path("cancel_appointment/<appointment_id>/", views.cancel_appointment, name="cancel_appointment"),
    path("activate_appointment/<appointment_id>/", views.activate_appointment, name="activate_appointment"),
    path("complete_appointment/<appointment_id>/", views.complete_appointment, name="complete_appointment"),

    path("payments/", views.payments, name="payments"),

    path("notifications/", views.notifications, name="notifications"),
    path("mark_noti_seen/<id>/", views.mark_noti_seen, name="mark_noti_seen"),
    
    path("profile/", views.profile, name="profile"),
]

userauths/urls.py
from django.urls import path

from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
]

base/models.py
from django.db import models

from shortuuid.django_fields import ShortUUIDField

from doctor import models as doctor_models
from patient import models as patient_models


class Service(models.Model):
    image = models.FileField(upload_to="images", null=True, blank=True)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    available_doctors = models.ManyToManyField(
        doctor_models.Doctor, blank=True)

    def __str__(self):
        return f"{self.name} - {self.cost}"


class Appointment(models.Model):
    STATUS = [
        ('Scheduled', 'Scheduled'),
        ('Completed', 'Completed'),
        ('Pending', 'Pending'),
        ('Cancelled', 'Cancelled')
    ]

    service = models.ForeignKey(Service, on_delete=models.SET_NULL,
                                null=True, blank=True, related_name='service_appointments')
    doctor = models.ForeignKey(doctor_models.Doctor, on_delete=models.SET_NULL,
                               null=True, blank=True, related_name='doctor_appointments')
    patient = models.ForeignKey(patient_models.Patient, on_delete=models.SET_NULL,
                                null=True, blank=True, related_name='appointments_patient')
    appointment_date = models.DateTimeField(null=True, blank=True)
    issues = models.TextField(blank=True, null=True)
    symptoms = models.TextField(blank=True, null=True)
    appointment_id = ShortUUIDField(
        length=6, max_length=10, alphabet="1234567890")
    status = models.CharField(max_length=120, choices=STATUS)

    def __str__(self):
        return f"{self.patient.full_name} with {self.doctor.full_name}"


class MedicalRecord(models.Model):
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE)
    diagnosis = models.TextField()
    treatment = models.TextField()

    def __str__(self):
        return f"Medical Record for {self.appointment.patient.full_name}"


class LabTest(models.Model):
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE)
    test_name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    result = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.test_name}"


class Prescription(models.Model):
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE)
    medications = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"Prescription for {self.appointment.patient.full_name}"


class Billing(models.Model):
    patient = models.ForeignKey(patient_models.Patient, on_delete=models.SET_NULL,
                                null=True, blank=True,  related_name='billings')
    appointment = models.ForeignKey(
        Appointment, on_delete=models.CASCADE, related_name='billing', blank=True, null=True)
    sub_total = models.DecimalField(max_digits=10, decimal_places=2)
    tax = models.DecimalField(max_digits=10, decimal_places=2)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=120, choices=[
                              ('Paid', 'Paid'), ('Unpaid', 'Unpaid')])
    billing_id = ShortUUIDField(length=6, max_length=10, alphabet="1234567890")

    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Billing for {self.patient.full_name} - Total: {self.total}"

base/views.py
from django.shortcuts import render

# Create your views here.

templates/base/book_appointment.html
{% extends 'partials/base.html' %}

{% block content %}

<section class="container">
    <div class="row d-flex justify-content-center align-items-center">
        <div class="col-12 col-lg-5">
            <img class="img-fluid mt-4" style="width: 100%; height: 550px; object-fit: cover; border-radius: 10px" src="{{ doctor.image.url }}" alt="" />
        </div>
        
        <div class="col-12 col-lg-7 p-4 rounded-3 bg-white">
            <h1 class="display-4 fw-bold mt-5">
                <span class=""><b>Dr. {{ doctor.full_name }}</b></span>
            </h1>

            <p class="fs-4 mt-4">{{ doctor.bio|default:"No bio available." }}</p>
        </div>
    </div>
</section>

<section class="container">
    <div class="">
        <h2 class="">Book Appointment</h2>
    </div>
    <form class="row" method="POST">
        {% csrf_token %}
        
        <div class="col-lg-12 mb-3">
            <label for="name" class="mb-2">Full Name</label>
            <input type="text" value="{{ patient.full_name }}" name="full_name" class="form-control" placeholder="John Doe" />
        </div>
        <div class="col-lg-6 mb-3">
            <label for="name" class="mb-2">Email</label>
            <input type="text" value="{{ patient.email }}" name="email" class="form-control" placeholder="johndoe@gmail.com" />
        </div>
        <div class="col-lg-6 mb-3">
            <label for="name" class="mb-2">Mobile Number</label>
            <input type="text" value="{{ patient.mobile }}" name="mobile" class="form-control" placeholder="+123 (456) 7890" />
        </div>
        <div class="col-lg-6 mb-3">
            <label for="name" class="mb-2">Gender</label>
            <select name="gender" id="" class="form-select pb-4">
                <option {% if patient.gender == "Male" %}selected{% endif %}value="Male">Male</option>
                <option {% if patient.gender == "Female" %}selected{% endif %}value="Female">Female</option>
            </select>
        </div>
        <div class="col-lg-6 mb-3">
            <label for="name" class="mb-2">Date of Birth</label>
            <input type="date" value="{{ patient.dob }}" name="dob" class="form-control" />
        </div>
        <div class="col-lg-12 mb-3">
            <label for="name" class="mb-2">Address</label>
            <input type="text" value="{{ patient.address }}" name="address" class="form-control" placeholder="123 Main Street" />
        </div>
        <div class="col-lg-12 mb-3">
            <label for="name" class="mb-2">Issues</label>
            <textarea name="issues" class="form-control" id="">{{ patient.issues }}</textarea>
        </div>

        <div class="col-lg-12 mb-3">
            <label for="name" class="mb-2">Symptoms</label>
            <textarea name="symptoms" class="form-control" id="">{{ patient.symptoms }}</textarea>
        </div>
        <div class="col-lg-12 mb-3">
            <button type="submit" class="btn btn-primary w-100">Continue <i class="fas fa-arrow-right ms-2"></i></button>
        </div>
    </form>
</section>
{% endblock content %}

templates/base/checkout.html
{% extends "partials/base.html" %} {% block content %}

<section class="container">
    <div class="row d-flex justify-content-center mt-3">
        <div class="col-lg-6">
            <div class="shadow p-3 rounded-3">
                <h3 class="mb-4">Bio Data</h3>
                <div class="row">
                    <div class="col-lg-12 mb-3">
                        <label for="name" class="mb-2">Full Name</label>
                        <input type="text" value="{{ billing.patient.full_name }}" readonly class="form-control bg-light" />
                    </div>
                    <div class="col-lg-6 mb-3">
                        <label for="name" class="mb-2">Email</label>
                        <input type="text" value="{{ billing.patient.email }}" readonly class="form-control bg-light" />
                    </div>
                    <div class="col-lg-6 mb-3">
                        <label for="name" class="mb-2">Mobile Number</label>
                        <input type="text" value="{{ billing.patient.mobile }}" readonly class="form-control bg-light" />
                    </div>
                    <div class="col-lg-6 mb-3">
                        <label for="name" class="mb-2">Gender</label>
                        <input type="text" value="{{ billing.patient.gender }}" readonly class="form-control bg-light" />
                    </div>
                    <div class="col-lg-6 mb-3">
                        <label for="name" class="mb-2">Date Of Birth</label>
                        <input type="text" value="{{ billing.patient.dob }}" readonly class="form-control bg-light" />
                    </div>
                    <div class="col-lg-12 mb-3">
                        <label for="name" class="mb-2">Address</label>
                        <input type="text" value="{{ billing.patient.address }}" readonly class="form-control bg-light" />
                    </div>
                </div>
            </div>

            <div class="shadow p-3 rounded-3 mt-4">
                <h3 class="mb-4">Doctor Description</h3>
                <div class="d-flex">
                    <div class="col-12 col-lg-5">
                        <img class="img-fluid mt-4" style="width: 100%; height: 450px; object-fit: cover; border-radius: 10px" src="{{ billing.appointment.doctor.image.url }}" alt="" />
                    </div>

                    <div class="col-12 col-lg-7 p-4 rounded-3 bg-white">
                        <h3 class="fw-bold mt-5">
                            <span class=""><b>Dr. {{ billing.appointment.doctor.full_name }}</b></span>
                        </h3>
                        <p class="fs-5 mt-4">{{ billing.appointment.doctor.bio|default:"" }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="shadow p-3 rounded-3">
                <div class="d-flex justify-content-between">
                    <p class="fw-semibold fs-5">Sub-total</p>
                    <p class="fs-5">${{ billing.subtotal }}</p>
                </div>

                <div class="d-flex justify-content-between">
                    <p class="fw-semibold fs-5">VAT</p>
                    <p class="fs-5">${{ billing.tax }}</p>
                </div>

                <div class="d-flex justify-content-between">
                    <p class="fw-bold fs-4">Total</p>
                    <p class="fw-bold fs-4">${{ billing.total }}</p>
                </div>
                <div class="mt-4">
                    <button type="button" id="stripe-payment" class="btn text-white w-100" style="background-color: blueviolet">Pay With Stripe <i class="fas fa-credit-card ms-2"></i></button>
                    <div id="paypal-button-container" class="mt-3"></div>
                </div>                
            </div>
        </div>
    </div>
</section>

<script src="https://www.paypal.com/sdk/js?client-id={{ paypal_client_id }}&currency=USD"></script>
<script src="https://js.stripe.com/v3/"></script>

<script>
    var stripe = Stripe("{{ stripe_public_key }}");
    var checkoutButton = document.getElementById("stripe-payment");

    try {
        checkoutButton.addEventListener("click", function () {
            var email = "EMAIL_HERE";

            checkoutButton.innerHTML = "Processing <i class='fas fa-spinner fa-spin ms-2'></i>";

            fetch("/stripe_payment/BILLING_ID_HERE/", {
                method: "POST",
                body: JSON.stringify({ email: email }),
            })
                .then(function (response) {
                    return response.json();
                })
                .then(function (session) {
                    return stripe.redirectToCheckout({ sessionId: session.sessionId });
                })
                .then(function (result) {
                    if (result.error) {
                        alert(result.error.message);
                    }
                })
                .catch(function (error) {
                    console.log("Error: ", error);
                });
        });
    } catch (error) {
        console.log(error);
    }
</script>

<script>
    function initPayPalButton() {
        paypal
            .Buttons({
                style: {
                    shape: "rect",
                    color: "gold",
                    layout: "vertical",
                    label: "paypal",
                },

                createOrder: function (data, actions) {
                    return actions.order.create({
                        purchase_units: [{ amount: { currency_code: "USD", value: "TOTAL_HERE" } }],
                    });
                },

                onApprove: function (data, actions) {
                    return actions.order.capture().then(function (orderData) {
                        // Full available details
                        console.log("Capture result", orderData, JSON.stringify(orderData, null, 2));

                        // Show a success message within this page, for example:
                        const element = document.getElementById("paypal-button-container");
                        element.innerHTML = "";
                        element.innerHTML = "<h5>Verifying payment...</h5>";
                        window.location.href = `/paypal_payment_verify/BILLING_ID_HERE/?transaction_id=${orderData.id}`;
                    });
                },

                onError: function (err) {
                    console.log(err);
                },
            })
            .render("#paypal-button-container");
    }
    initPayPalButton();
</script>

{% endblock %}

templates/base/index.html
{% extends 'partials/base.html' %} {% block content %}
<section class="container">
  <div class="row d-flex justify-content-center align-items-center">
    <div class="col-12 col-lg-7 p-4 rounded-3 bg-white">
      <h1 class="display-4 fw-bold mt-5">
        <span class="text-primary"><b>Extraordinary</b></span> Care is Right
        Here With <span class="text-primary">You.</span>
      </h1>
      <p class="fs-4 mt-4">
        Every patient is different, every smile is unique, We prioritize safety
        with health checks, contactless check-in, enhanced PPE, and more.
      </p>
      <div class="d-flex align-items-center gap-2 mt-5">
        <a href="{% url 'userauths:sign-up' %}" class="btn btn-primary btn-lg">
          Create Account <i class="fas fa-user-plus ms-1"></i>
        </a>
        <a href="#ourService" class="btn btn-outline-primary btn-lg">
          Book Appointment <i class="fas fa-arrow-right ms-2"></i>
        </a>
      </div>
    </div>
    <div class="col-12 col-lg-5">
      <img
        class="img-fluid mt-4"
        style="
          width: 100%;
          height: 350px;
          object-fit: cover;
          border-radius: 10px;
        "
        src="https://indiaeducationdiary.in/wp-content/uploads/2024/03/GettyImages-1217096099-3.jpg"
        alt=""
      />
    </div>
  </div>
</section>

<section class="container mt-5">
  <div class="py-4">
    <h2 class="" id="ourService">Our Services</h2>
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis,
      reiciendis.
    </p>
  </div>
  <div class="row">
    {% for s in services %}
    <div class="col-lg-3">
      <div class="card mb-4 shadow">
        <a href="{% url 'base:service_detail' s.id %}">
          <img
            src="{{s.image.url}}"
            alt="course"
            style="height: 200px; object-fit: cover"
            class="card-img-top"
          />
        </a>
        <div class="card-body">
          <h4 class="mb-2 text-truncate-line-2">
            <a
              href="{% url 'base:service_detail' s.id %}"
              class="text-inherit text-dark text-decoration-none"
              >{{s.name}}</a
            >
          </h4>
          <p>{{s.description|truncatechars:40}}</p>
          <div class="mt-2">
            <span class="fw-semibold"
              >Doctors Available: {{s.available_doctors.all.count}}</span
            >
            <div class="lh-1 mt-3">
              <span class="text-dark fw-bold fs-4">${{s.cost}}</span>
            </div>
            <a
              href="{% url 'base:service_detail' s.id %}"
              class="btn btn-sm btn-primary mt-3"
              >Book Appointment <i class="fas fa-arrow-right ms-2"></i
            ></a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</section>

<section class="container mt-5">
  <div class="row d-flex align-items-center">
    <div class="col-lg-6">
      <h1 class="fw-bold">Get Appointment Now!</h1>
      <p class="text-secondary">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus et
        voluptate omnis accusantium. Tenetur explicabo vero quo dolore.
        Repudiandae itaque accusantium dolor ab. Blanditiis esse tempore ut ad
        accusantium nihil?
      </p>

      <div class="d-flex align-items-center gap-2 mt-5">
        <a href="#ourService" class="btn btn-outline-primary">
          <i class="fas fa-video ms-1"></i>View Services
        </a>
        <a href="{% url 'userauths:sign-up' %}" class="btn btn-primary">
          Create Account <i class="fas fa-user-plus ms-1"></i>
        </a>
        <button class="btn btn-primary">
          Learn More <i class="fas fa-arrow-right ms-1"></i>
        </button>
      </div>
    </div>
    <div class="col-lg-6">
      <img
        src="https://www.mckenzielake.com/wp-content/uploads/2022/06/iStock-1299777111.jpg"
        class="img-fluid rounded"
        style="height: 400px"
        alt=""
      />
    </div>
  </div>
</section>
{% endblock content %}

templates/base/payment_status.html
{% extends 'partials/base.html' %} {% block content %}
<section class="container">
    <div class="container">
        {% if payment_status == "paid" %}

        <div class="d-flex justify-content-center flex-column align-items-center mb-5">
            <i class="fas fa-check-circle text-success display-1"></i>
            <h1>Appointment Scheduled Successfully</h1>
            <p class="text-success">Thanks for boking an appointment <i class="fas fa-check-circle"></i></p>
            <a href="{% url 'patient:dashboard' %}" class="btn btn-success d-flex align-items-center">My Dashboard <i class="bi bi-grid-fill ms-2"></i></a>
        </div>
        {% endif %} {% if payment_status == "failed" %}

        <div class="d-flex justify-content-center flex-column align-items-center mb-5">
            <i class="fas fa-exclamation-triangle fa-flip text-danger display-1"></i>
            <h1>Appointment Scheduled Failed</h1>
            <p>We couldn't process your payment, please try again later. Thank you</p>
        </div>
        {% endif %}
    </div>
</section>
{% endblock content %}

templates/base/service_detail.html
{% extends 'partials/base.html' %}
{% block content %}
        <section class="container">
            <div class="row d-flex justify-content-center align-items-center">
                <div class="col-12 col-lg-7 p-4 rounded-3 bg-white">
                    <h1 class="display-4 fw-bold mt-5">
                        <span class="text-primary"><b>{{ service.name }}</b></span>
                    </h1>
                    <p class="fs-4 mt-4">{{ service.description }}</p>
                    
                </div>
                <div class="col-12 col-lg-5">
                    <img class="img-fluid mt-4" style="width: 100%; height: 350px; object-fit: cover; border-radius: 10px" src="{{ service.image.url }}" alt="" />
                </div>
            </div>
        </section>

        <section class="container">
            <div class="">
                <h2 class="">Available Doctors</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Debitis, reiciendis.</p>
            </div>
            <div class="">
        {% for d in service.available_doctor.all %}
                    <div class="p-1 mb-4 shadow d-flex align-items-center">
                        <a href="course-detail.html">
                            <img src="{{ d.image.url }}" alt="course" style="width: 70px; height: 70px; object-fit: cover; border-radius: 5px" class="card-img-top" />
                        </a>
                        <div class="card-body">
                            <div class="mt-2 d-flex justify-content-between align-items-center">
                                <div>
                                    <h5 class="mb-1 text-truncate-line-2"><a href="course-detail.html" class="text-inherit text-dark text-decoration-none">{{ d.full_name}}</a></h5>
                                    <div class="d-flex gap-2">
                                        <p class="fw-semibold mt-0 mb-0">Time Available:</p>
                                        <p class="mt-0 mb-0">{{ d.next_available_appointment }}</p>
                                    </div>
                                    <div class="d-flex gap-2">
                                        <p class="fw-semibold mt-0 mb-0">Price:</p>
                                        <p class="mt-0 mb-0">${{ service.cost }}</p>
                                    </div>
                                </div>

                                <div>
                                    <a href="{% url 'base:book_appointment' service.id d.id %}" class="btn btn-primary me-4">Book Now <i class="fas fa-arrow-right ms-2"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </section>

{% endblock %}